apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
  - path: cert-manager
    repoURL: https://github.com/crossvale-inc/msp-open-gitops.git
    targetRevision: main
  - path: kubernetes-dashboard
    repoURL: https://github.com/crossvale-inc/msp-open-gitops.git
    targetRevision: main
    directory:
      recurse: true
      jsonnet: {}
      exclude: '{kubernetes-dashboard-values.yaml}'
  - path: efk-stack
    repoURL: https://github.com/crossvale-inc/msp-open-gitops.git
    targetRevision: main
  - path: prometheus-eks
    repoURL: https://github.com/crossvale-inc/msp-open-gitops.git
    targetRevision: main
    directory:
      recurse: true
      jsonnet: {}
      exclude: '{prometheus-stack-values.yaml}'
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
