apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: app-of-apps-freemium
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
  - path: cert-manager
    repoURL: https://github.com/crossvale-inc/msp-gitops-apps-freemium.git
    targetRevision: feature/all-values
  - path: eks-dashboard
    repoURL: https://github.com/crossvale-inc/msp-gitops-apps-freemium.git
    targetRevision: feature/all-values
    directory:
      recurse: true
      jsonnet: {}
      exclude: '{eks-dashboard-values.yaml}'
  - path: efk-stack
    repoURL: https://github.com/crossvale-inc/msp-gitops-apps-freemium.git
    targetRevision: feature/all-values
  - path: prometheus-eks
    repoURL: https://github.com/crossvale-inc/msp-gitops-apps-freemium.git
    targetRevision: feature/all-values
    directory:
      recurse: true
      jsonnet: {}
      exclude: '{prometheus-stack-values.yaml}'
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
