apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: prometheus-stack
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 56.21.0
    chart: kube-prometheus-stack
    helm:
      valueFiles:
      - $values/prometheus-eks/prometheus-stack-values.yaml
  - repoURL: https://github.com/crossvale-inc/msp-open-gitops.git
    targetRevision: main
    ref: values  
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
