apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack-freemium
  namespace: argocd
spec:
  destination:
    namespace: loki-stack-freemium
    server: https://kubernetes.default.svc
  project: default
  source:
  - repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.9.10
    chart: loki-stack
    helm:
      valueFiles:
      - $values/loki-eks/values.yaml
  - repoURL: https://github.com/crossvale-inc/msp-gitops-apps-freemium.git
    targetRevision: main
    ref: values
  syncPolicy:
    automated: {}
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true