grafana:
  enabled: true
loki:
 env:
   - name: AWS_ACCESS_KEY_ID
     value: AKIA3WLCOPL57CFJASXI
   - name: AWS_SECRET_ACCESS_KEY
     value: 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
 config:
   schema_config:
     configs:
       - from: 2021-05-12
         store: boltdb-shipper
         object_store: s3
         schema: v11
         index:
           prefix: loki_index_
           period: 24h
   storage_config:
     aws:
       s3: s3://eu-west-1/eks-freemium-stack
       s3forcepathstyle: true
       bucketnames: eks-freemium-stack
       region: eu-west-1
       insecure: false