resources:
  requests:
    cpu: "1"
    memory: "2048Mi"
  limits:
    cpu: "1"
    memory: "2048Mi"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 50Gi