apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-freemium
  namespace: argocd
spec:
  destination:
    namespace: elasticsearch
    server: https://kubernetes.default.svc
  project: default
  source:
    - repoURL: https://helm.elastic.co
      chart: elasticsearch
      targetRevision: 8.5.1
      helm:
        valueFiles:
        - $values/efk-stack/elasticsearch-values.yaml
    - repoURL: https://github.com/crossvale-inc/msp-gitops-apps-freemium.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true