apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-freemium
  namespace: argocd
spec:
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jqPathExpressions:
      - '.spec.volumeClaimTemplates[]?'
  destination:
    namespace: elasticsearch-freemium
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://helm.elastic.co
      chart: elasticsearch
      targetRevision: 8.5.1
      helm:
        valueFiles:
        - $values/efk-stack/elasticsearch-values.yaml
    - repoURL: https://github.com/crossvale-inc/msp-gitops-apps-freemium.git
      targetRevision: feature/all-values
      ref: values
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true